### ISSUE TITLE
Info on usage smart-web

### ISSUE THREAD

**Issue by docop** [Luffy404/smartapp-website#1]
Hi  Just find out your project and it look quite interesting, as i got a lamp bulb but no remote and only want to control localy. So is your 'script' it's running on windows ? Or you need a centos7 to run it...  If you have a how to, that might give me more info.
thanks in advance

**Comment by Luffy404** [comment]
Hey, I scrapped this Project since there is a already made version (https://github.com/home-assistant/core), I'm still trying to continue developing this in my free time but I would recommend using the other project.

**Comment by docop** [comment]
thanks for that.
